#! /bin/sh

# todo: show global status like 'Threads_running' && --max-load
#   set to 10?? (nproc on db2==16, on db=32)
# todo: make hash functions configurable somehow -
#   current code requires 'fnv1a_64' to be installed.
# chunk strategy:
#   - we have relatively low concurrency on heavy duty queries on big tables
#   - therefore using high chunk time matches regular query load, and 
#     facillitates checksumming large tables.
 

usage_exit() {
	arghelp="[start-full|resume-full|start-partial|resume-partial]";
	echo "usage: `basename $0` $arghelp";
	exit 0;
}

case $1 in
	"start-full") 
		ignore=""; 
		jobstate="--truncate-replicate-table";;
	"resume-full") 
		ignore=""; 
		jobstate="--resume";;
	"start-partial") 
		ignore="--ignore-tables-regex ^__";
		jobstate="--truncate-replicate-table";;
	"resume-partial") 
		ignore="--ignore-tables-regex ^__";
		jobstate="--resume";;
	*)
		usage_exit;;
esac

[ ! -z "$MYSQL_SOCKET" ] && socketarg="--socket $MYSQL_SOCKET" || socketarg=""

pt-table-checksum --user root $socketarg \
	--nocheck-plan --chunk-time=300 \
	--function 'fnv1a_64' $jobstate $ignore

