#! /bin/sh

# todo: show global status like 'Threads_running' && --max-load
#   set to 10?? (nproc on db2==16, on db=32)
# todo: make hash functions configurable somehow -
#   current code requires 'fnv1a_64' to be installed.
# chunk strategy:
#   - we have relatively low concurrency on heavy duty queries on big tables
#   - therefore using high chunk time matches regular query load, and 
#     facillitates checksumming large tables.
 

usage_exit() {
	arghelp="[start-full|resume-full|start-partial|resume-partial]";
	echo "usage: `basename $0` $arghelp";
	exit 0;
}

sqlreport(){  # TODO: integrate
	# empty if no errors
	mysql -u root -S /var/run/mysqld/mysqld1.sock <<EOF
		SELECT db, tbl, SUM(this_cnt) AS total_rows, COUNT(*) AS chunks
		FROM percona.checksums
		WHERE (
			master_cnt <> this_cnt
			OR master_crc <> this_crc
			OR ISNULL(master_crc) <> ISNULL(this_crc))
		GROUP BY db, tbl;
EOF
}

checksumreport() { # TODO: integrate
	/usr/bin/pt-table-checksum \
		--user root \
		--socket /var/run/mysqld/mysqld1.sock \
		--no-check-binlog-format \
		--ignore-tables-regex '^__' \
		--replicate-check-only
}

case $1 in
	"start-full") 
		ignore=""; 
		jobstate="--truncate-replicate-table";;
	"resume-full") 
		ignore=""; 
		jobstate="--resume";;
	"start-partial") 
		ignore="--ignore-tables-regex ^__";
		jobstate="--truncate-replicate-table";;
	"resume-partial") 
		ignore="--ignore-tables-regex ^__";
		jobstate="--resume";;
	*)
		usage_exit;;
esac

[ ! -z "$MYSQL_SOCKET" ] && socketarg="--socket $MYSQL_SOCKET" || socketarg=""

pass=`awk -F= '/^pass/{print $2}' ~/.my.cnf`
[ ! -z "$pass" ] && passarg="--password $pass" || passarg=""

pt-table-checksum --user root $passarg $socketarg \
	--no-check-binlog-format --nocheck-plan --chunk-time=300 \
	--function 'fnv1a_64' $jobstate $ignore

